### PR TITLE
Added features:ReactiveUrsaWindow<TViewModel> and ReactiveUrsaView.

### PR DESCRIPTION
**Pull request by WCKYWCKF**
Ursa's intent is to expand the functionality of the original AvaloniaUI, so the ReactiveUI version should be implemented for UrsaWindow and UrsaView.

1.added class ReactiveUrsaWindow<TViewModel>.
2.added class ReactiveUrsaView<TViewModel>.
3.New project dependencies have been added Avalonia.ReactiveUI(11.1.1) 
4.Fixed the ambiguity of method calls between System.ObservableExtensions.Subscribe and Irihi.Avalonia.Shared.Helpers.ObservableExtension.Subscribe.

### CODE REVIEW

**Comment by rabbitism** [comment]
Ursa does not rely on any specific MVVM design, so introducing ReactiveUI dependency is not acceptable. It is harmful to users consuming other MVVM frameworks.

**Comment by WCKYWCKF** [comment]
I think you have a point. Would it be better to publish #410 as a package similar to the Avalonia.ReactiveUI Nuget package?

**Comment by rabbitism** [comment]
> I think you have a point. Would it be better to publish #410 as a package similar to the Avalonia.ReactiveUI Nuget package?

Yes, it should be delivered separately as Ursa.ReactiveUIExtension, like the Prism extension.

**Comment by WCKYWCKF** [comment]
I'm going to refer to the code for Avalonia.ReactiveUI to redesign #410 and add a Ursa.ReactiveUI project and deliver it separately. What do you think?

**Pull request closed without merging**
