### PR TITLE
FullScreen overlay dialog updates

### PR DESCRIPTION
**Pull request by rabbitism**
1. make full-screen dialog draggable to trigger window moving
2. Make sure full-screen is always full-screen when resizing window.

### CODE REVIEW

**Review by WCKYWCKF — APPROVED** [review]
The branch has been pulled locally for testing.（Win11）

**Comment by WCKYWCKF** [comment]
lsseus#400 update is not complete. The Window.RaiseEvent response when OverlayDialogOptions.FullScreen = true has been fixed completely, but the drag effect only works in UrsaWindow, not in Window or ReactiveWindow<T>. Sorry, this is my negligence, I just tried the demo and didn't reference it to my own project for testing and reported that #400 is no longer problematic. The issue was discovered when I was updating the project's dependencies today.

**Comment by rabbitism** [comment]
> lsseus#400 update is not complete. The Window.RaiseEvent response when OverlayDialogOptions.FullScreen = true has been fixed completely, but the drag effect only works in UrsaWindow, not in Window or ReactiveWindow<T>. Sorry, this is my negligence, I just tried the demo and didn't reference it to my own project for testing and reported that #400 is no longer problematic. The issue was discovered when I was updating the project's dependencies today.

We introduced a new flag, you can set IsTopLevel=true in your OverlayDialogHost to make it work.

**Comment by WCKYWCKF** [comment]
Well, maybe I should read [What's Changed] before asking questions.😂

**Pull request merged**
