### PR TITLE
Respect OffScreenMargin for elements in chrome layer.

### LINKED ISSUE #438: UrsaWindow最大化问题
最大化之后，标题栏显示不全，有点像整体位置偏上移动了一点

### PR DESCRIPTION
**Pull request by rabbitism**
Close #438

### CODE REVIEW

**Comment by rabbitism** [comment]
@wslsj888 @JusterZhu  please hep to review

**Comment by wslsj888** [comment]
well done!

**Comment by JusterZhu** [comment]
When using the OffScreenMargin property to resolve the current issue, has it been tested on different resolutions?

**Comment by rabbitism** [comment]
> When using the OffScreenMargin property to resolve the current issue, has it been tested on different resolutions?

This is a fixed value, and only has a valid value on os-windows.

**Review by JusterZhu — APPROVED** [review]
Later, we may need to label the operating system platform where the issue occurs on the label.

**Pull request merged**
