### PR TITLE
Clock

### PR DESCRIPTION
**Pull request by rabbitism**

### CODE REVIEW

**Comment by zdpcdt** [comment]
Adjusting the length ratio of the hour and minute hands may be better.
image

**Comment by rabbitism** [comment]
How is the ratio set?

**Comment by zdpcdt** [comment]
> How is the ratio set?

Perhaps we should set the golden ratio:
Hour: Minute: Second = 0.618 : 1 : 1

**Comment by rabbitism** [comment]
Updated.

**Comment by zdpcdt** [comment]
LGTM

**Review by zdpcdt — APPROVED** [review]

**Pull request merged**
