### PR TITLE
add IsUpdateValueWhenLostFocus

### LINKED ISSUE #200: Numericbox 支持 IsUpdateValueWhenLostFocus
- IsUpdateValueWhenLostFocus
   - False： user have to enter to trigger，Even lost focus
   - True： trigger value change while lost focus

### PR DESCRIPTION
**Pull request by heartacker**
fix #200

### CODE REVIEW

**Comment by heartacker** [comment]
merge read/write button first and I will go ahead

**Comment by rabbitism** [comment]
Displayed text should either go back to old value or go to new value, it's ambiguous to have a state that displayed text is completely unrelated to the actual value.

**Comment by heartacker** [comment]
> Displayed text should either go back to old value or go to new value, it's ambiguous to have a state that displayed text is completely unrelated to the actual value.

we need to do this https://github.com/irihitech/Ursa.Avalonia/issues/201
image

**Comment by rabbitism** [comment]
超过最大最小无效这种判断应该是user在application中依据validation attribute来显示DataValidationError的，不应该内置到控件中。

**Pull request closed without merging**
